
Bad key "text.kerning_factor" on line 4 in
/home/ihaide/miniconda3/envs/metrics_test/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
file number: Traceback (most recent call last):
  File "uncertainty2d_nojup.py", line 66, in <module>
    first = input('file number: ')
OSError: [Errno 9] Bad file descriptor

Bad key "text.kerning_factor" on line 4 in
/home/ihaide/miniconda3/envs/metrics_test/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
file number: Traceback (most recent call last):
  File "uncertainty2d_nojup.py", line 66, in <module>
    first = input('file number: ')
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "uncertainty2d_nojup.py", line 1, in <module>
    import h5py as h5
ModuleNotFoundError: No module named 'h5py'
